// <auto-generated/>
using UnityEngine;
using XWEngine;
using ZLC.EventSystem.MessageQueue;
using ZLC.WindowSystem;
namespace XWEngine.UGUI{
    public class WindowMessageQueue : AMainThreadMQ<WindowMessage>
    {
        public static WindowMessageQueue Instance
        {
            get{
                if(_instance == null)
                {
                    var newObject = new GameObject("WindowMessageQueue");
                    GameObject.DontDestroyOnLoad(newObject);
                    _instance = newObject.AddComponent<WindowMessageQueue>();
                }
                return _instance;
            }
        }
        private static WindowMessageQueue _instance;
    }
}